@echo off
setlocal enabledelayedexpansion
chcp 65001 >nul

echo ==========================================
echo       Cap 完整打包脚本 (Windows)
echo ==========================================
echo.

:: 设置颜色支持
set "RED=[91m"
set "GREEN=[92m"
set "YELLOW=[93m"
set "BLUE=[94m"
set "RESET=[0m"

:: ==========================================
:: 第一部分: 环境检查
:: ==========================================
echo %BLUE%[阶段 1/5] 环境检查%RESET%
echo.

:: 1. 检查 Node.js 和 pnpm
echo [1.1] 检查 Node.js...
where node >nul 2>&1
if %errorlevel% neq 0 (
    echo %RED%[错误]%RESET% 未找到 Node.js - 请先安装 Node.js 20+
    pause
    exit /b 1
)
for /f "tokens=*" %%i in ('node --version') do set NODE_VERSION=%%i
echo %GREEN%[✓]%RESET% Node.js 版本: %NODE_VERSION%

echo [1.2] 检查 pnpm...
where pnpm >nul 2>&1
if %errorlevel% neq 0 (
    if exist "%APPDATA%\npm\pnpm.cmd" (
        set "PATH=%APPDATA%\npm;%PATH%"
    ) else (
        echo %RED%[错误]%RESET% 未找到 pnpm
        echo 正在安装 pnpm...
        call npm install -g pnpm
        if %errorlevel% neq 0 (
            echo %RED%[错误]%RESET% pnpm 安装失败
            pause
            exit /b 1
        )
    )
)
for /f "tokens=*" %%i in ('pnpm --version') do set PNPM_VERSION=%%i
echo %GREEN%[✓]%RESET% pnpm 版本: %PNPM_VERSION%

:: 2. 检查 Rust
echo [1.3] 检查 Rust/Cargo...
if exist "%USERPROFILE%\.cargo\bin\cargo.exe" (
    set "PATH=%USERPROFILE%\.cargo\bin;%PATH%"
)
where cargo >nul 2>&1
if %errorlevel% neq 0 (
    echo %RED%[错误]%RESET% 未找到 Cargo Rust
    echo 请访问 https://rustup.rs/ 安装 Rust
    pause
    exit /b 1
)
for /f "tokens=*" %%i in ('cargo --version') do set CARGO_VERSION=%%i
echo %GREEN%[✓]%RESET% %CARGO_VERSION%

:: 3. 检查 LLVM
echo [1.4] 检查 LLVM (libclang)...
set "LLVM_FOUND=0"
if exist "C:\Program Files\LLVM\bin\libclang.dll" (
    set "LLVM_FOUND=1"
    set "LIBCLANG_PATH=C:\Program Files\LLVM\bin"
)
if exist "%USERPROFILE%\.cap_build_tools\llvm\bin\libclang.dll" (
    set "LLVM_FOUND=1"
    set "LIBCLANG_PATH=%USERPROFILE%\.cap_build_tools\llvm\bin"
)
if "%LLVM_FOUND%"=="0" (
    echo %YELLOW%[警告]%RESET% 未找到 LLVM，某些功能可能无法使用
) else (
    echo %GREEN%[✓]%RESET% LLVM 找到: %LIBCLANG_PATH%
)

:: ==========================================
:: 第二部分: 创建 .env 文件
:: ==========================================
echo.
echo %BLUE%[阶段 2/5] 配置环境%RESET%
echo.

if not exist ".env" (
    echo [2.1] 创建 .env 文件...
    (
        echo # Cap Environment Configuration
        echo # Auto-generated by build script
        echo.
        echo # Database (仅用于 web，桌面应用不需要^)
        echo DATABASE_URL="mysql://root:password@localhost:3306/cap"
        echo.
        echo # S3 Storage (仅用于 web，桌面应用不需要^)
        echo NEXT_PUBLIC_URL="http://localhost:3000"
        echo NEXT_PUBLIC_ENVIRONMENT="development"
        echo.
        echo # Desktop build
        echo TAURI_ENV="development"
    ) > .env
    echo %GREEN%[✓]%RESET% .env 文件已创建
) else (
    echo %GREEN%[✓]%RESET% .env 文件已存在
)

:: ==========================================
:: 第三部分: 安装依赖
:: ==========================================
echo.
echo %BLUE%[阶段 3/5] 安装依赖%RESET%
echo.

echo [3.1] 检查 node_modules...
if not exist "node_modules" (
    echo 正在安装 Node 依赖...
    call pnpm install
    if %errorlevel% neq 0 (
        echo %RED%[错误]%RESET% 依赖安装失败
        pause
        exit /b 1
    )
    echo %GREEN%[✓]%RESET% Node 依赖安装完成
) else (
    echo %GREEN%[✓]%RESET% Node 依赖已安装
)

echo [3.2] 设置 FFmpeg 和原生依赖...
if not exist "target\native-deps\include\libavutil\avutil.h" (
    echo 正在设置 FFmpeg...
    call node scripts/setup.js
    if %errorlevel% neq 0 (
        echo %RED%[错误]%RESET% FFmpeg 设置失败
        pause
        exit /b 1
    )
    echo %GREEN%[✓]%RESET% FFmpeg 和原生依赖设置完成
) else (
    echo %GREEN%[✓]%RESET% FFmpeg 已设置，跳过
)

:: ==========================================
:: 第四部分: 清理旧构建
:: ==========================================
echo.
echo %BLUE%[阶段 4/5] 清理旧构建%RESET%
echo.

echo [4.1] 清理 Rust 构建缓存...
if exist "target\debug" (
    echo 删除 target\debug 目录...
    rmdir /s /q target\debug 2>nul
)
if exist "target\release" (
    echo 删除 target\release 目录...
    rmdir /s /q target\release 2>nul
)
echo %GREEN%[✓]%RESET% Rust 构建缓存已清理 (保留 native-deps)

echo [4.2] 清理前端构建缓存...
if exist "apps\desktop\.vinxi" (
    rmdir /s /q apps\desktop\.vinxi 2>nul
)
if exist "apps\desktop\.output" (
    rmdir /s /q apps\desktop\.output 2>nul
)
echo %GREEN%[✓]%RESET% 前端构建缓存已清理

:: ==========================================
:: 第五部分: 执行构建
:: ==========================================
echo.
echo %BLUE%[阶段 5/5] 开始构建打包%RESET%
echo ==========================================
echo.
echo 这将需要 15-20 分钟，请耐心等待...
echo.

:: 记录开始时间
set START_TIME=%TIME%

:: 执行构建
call pnpm tauri:build

:: 检查构建结果
if %errorlevel% equ 0 (
    echo.
    echo ==========================================
    echo %GREEN%[SUCCESS] 构建成功%RESET%
    echo ==========================================
    echo.
    
    :: 查找安装包
    set "BUNDLE_DIR=apps\desktop\src-tauri\target\release\bundle"
    
    if exist "%BUNDLE_DIR%\nsis" (
        echo %GREEN%[安装包位置]%RESET%
        echo NSIS 安装程序: %BUNDLE_DIR%\nsis\
        dir /b "%BUNDLE_DIR%\nsis\*.exe" 2>nul
        echo.
        
        :: 打开文件夹
        start "" explorer "%CD%\%BUNDLE_DIR%\nsis"
    )
    
    if exist "%BUNDLE_DIR%\msi" (
        echo MSI 安装程序: %BUNDLE_DIR%\msi\
        dir /b "%BUNDLE_DIR%\msi\*.msi" 2>nul
        echo.
    )
    
    echo 总用时: 从 %START_TIME% 到 %TIME%
    echo.
) else (
    echo.
    echo ==========================================
    echo %RED%✗ 构建失败%RESET%
    echo ==========================================
    echo.
    echo 请检查上方的错误信息
    echo.
    echo 常见问题:
    echo 1. 确保所有依赖已正确安装
    echo 2. 检查网络连接（构建过程需要下载依赖）
    echo 3. 确保有足够的磁盘空间（至少 10GB）
    echo.
)

pause
